### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#1]
Будут ли добавлены коммиты с примерами использования и подключением ts к проекту + настройка tsconfig?

Для пропсов компонента использовать type или interface? На лекции был показан пример с type, но я видел как используют interface, а не type. Как правильнее, ведь они оба описывают объект?

Пропсы в ts делать обязательными? В каких случаях допустимо делать пропсы необязательными?

**Comment by sashasushko** [comment]
> Будут ли добавлены коммиты с примерами использования и подключением ts к проекту + настройка tsconfig?

Добавлены

**Comment by sashasushko** [comment]
> Для пропсов компонента использовать type или interface? На лекции был показан пример с type, но я видел как используют interface, а не type. Как правильнее, ведь они оба описывают объект?

Можно так, как удобно. В проекте есть пример и одного, и другого.

**Comment by sashasushko** [comment]
> Пропсы в ts делать обязательными? В каких случаях допустимо делать пропсы необязательными?

Пропсы по умолчанию все обязательные в TS. Если нужно наоборот - сделать необязательными - нужно это сделать явно.
