### ISSUE TITLE
Б37 и combineReducers

### ISSUE THREAD

**Issue by balesniy** [htmlacademy-react/guess-melody#2]
> Б37. Главный файл в каждой папке, называется так же, как папка, например app/app.jsx. **Название index.js используется только для входной точки приложения**

`src/reducer/index.js` тут поправить или в критериях?

**Comment by sashasushko** [comment]
На эту проверку нужно будет в проекте переименовать `index.js`.

**Comment by sashasushko** [comment]
А проблему в https://github.com/htmlacademy/yomoyo закинь, пожалуйста.
