### ISSUE TITLE
Нейминг интерфейсов

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#3]
Я считал, что именование интерфейсов с заглавной "I" + название компонента, считается хорошей практикой. Столкнулся с тем, что конфиг запрещает такой нейминг. С чем это связано?

![image](https://user-images.githubusercontent.com/35527172/69494154-1f072a00-0ec9-11ea-9bb4-9a516bae615c.png)

**Comment by sashasushko** [comment]
@nullorone это избыточно. Ровно так же, как писать для типов префикс `T`, поэтому линтер не пропускает.

В каких-то проектах может быть наоборот. Решает команда.
