### ISSUE TITLE
React.FunctionComponent

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#4]
В файле welcome-screen.tsx используется запись `const WelcomeScreen: React.FunctionComponent<Props> = (props) => ` в каких случаях необходимо явно указывать, что это функциональный компонент? Я попробовал следующую запись `const WelcomeScreen = (props: Props) => ` и ошибок нет =|

**Comment by sashasushko** [comment]
@nullorone, `React.FunctionComponent` - дженерик для удобства. Он сам докидывает типы для пропсов, вроде `children`.

Работать будет и без него.
