### ISSUE TITLE
Переиспользование интерфейсов с исключениями

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#5]
В примере показана конструкция `Subtract`, но я слышал о конструкциях `Pick<Interface, Exclude<....>>`, а также `Omit<>`. Правильно ли я понял, что эти конструкции реализуют одинаковую логику - сохраняют в тип/свойство результат вычитания из интерфейса определенных свойств?

Для хоков не подойдет конструкция `Assign`?

p.s. при попытках использования Pick-Exclude и Omit, столкнулся с ограничениями линтера - использование бэктиков, а не одинарных или двойных кавычек. Как я понял, тс не понимает в таких конструкциях бэктики :(

**Comment by sashasushko** [comment]
@nullorone закинь, пожалуйста, пример кода с бэктиками и ошбки в репозиторий https://github.com/htmlacademy/yomoyo

**Comment by sashasushko** [comment]
@nullorone что до первого вопроса, то конструкций много - https://www.typescriptlang.org/docs/handbook/utility-types.html

Лучше всего будет ознакомиться с описанием каждой и выбирать ту, которая больше подходит.
