### ISSUE TITLE
Возврат классового компонента в ХОКах

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#6]
В примерах не указан тип возвращаемого значения у функций ХОКов. Линтер желает, чтобы я явно указывал возвращаемый тип. В других примерах с функциональными компонентами, мы используем конструкцию `React.FunctionComponent<интерфейс пропс>`, но в ХОКах у нас в качестве пропсы приходит компонент. Пытался использовать `JSX. ElementClass`, но линтер начинает ругаться на обязательные свойства и методы... Надо исключить неиспользуемые свойства и методы у `ElementClass` или существует какая-то иная конструкция для ХОКов?

**Comment by sashasushko** [comment]
@nullorone можно опустить этот момент, линтер кидает предупреждение, а не ошибку.

**Comment by sashasushko** [comment]
@nullorone к тому же обычно TypeScript сам понимает, что возвращает HOC.

**Comment by sashasushko** [comment]
@nullorone но чтобы разобраться до конца, рекомендую почитать доп.инфы. Например, https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/HOC.md
