### ISSUE TITLE
Ошибка EsLint

### ISSUE THREAD

**Issue by nullorone** [htmlacademy-react/guess-melody#7]
В тесте использую вызов пустой функции `preventDefault() {}`
![image](https://user-images.githubusercontent.com/35527172/69899916-ec07df00-137d-11ea-956a-77bab4a4855e.png)
Получаю ошибку EsLint, что функция не должна быть пустой. Исправлять линтер нельзя, как тогда разрешить эту ошибку линтера?
![image](https://user-images.githubusercontent.com/35527172/69899925-0f328e80-137e-11ea-907b-dd6ea6aa3a41.png)

**Comment by sashasushko** [comment]
@nullorone можешь коммент в тело добавить

**Comment by sashasushko** [comment]
@nullorone закинь ишью, пожалуйста, в https://github.com/htmlacademy/yomoyo

**Comment by sashasushko** [comment]
@nullorone и напиши, получится ли с комментом

**Comment by nullorone** [comment]
@sashasushko с таким комментом всё проходит
![image](https://user-images.githubusercontent.com/35527172/69997021-4793c180-1564-11ea-8805-31bd689ca768.png)

**Comment by sashasushko** [comment]
Спасибо
